### PR TITLE
Go slides

### PR DESCRIPTION
**Pull request by tebeka**
Slides for talks in the Go track.

### CODE REVIEW

**Review by tomer — CHANGES_REQUESTED** [review]
We have embedded all other presentations into the page. I suggest doing the same for these presentations as well. Also, please note that we've placed the presentations inside `<dl><dd>`.

**Comment by tebeka** [comment]
I can embed Eyal and Guy. Though Guy have additional files in Google drive.
Mine is a custom go present tool, I'll work on hosting it.

**Comment by tebeka** [comment]
@tomer I've embeded Guy's and Eyal's presentations. I can do an image for mine if you want.

**Comment by tomer** [comment]
I really don't care much, but we want users to be able to read content easily. Is it possible to convert the presentation to a PDF file or an HTML slideshow?

**Comment by tebeka** [comment]
@tomer I've added an iframe for my talk - ready to Go :)

**Comment by shaib** [comment]
@tomer is there a reason not to merge this?

**Comment by tbrisker** [comment]
Thanks @tebeka and @tomer !

**Pull request merged**
