### PR TITLE
Fixes #76 - Add 'Fork me on GitHub' ribbons

### LINKED ISSUE #76: Can we have a link back to GitHub?
AP is all about promoting open source software - a link back to the project on GitHub would help highlight this and attract potential contributors.

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by shaib** [comment]
The ribbons don't work well with the floating header. They roll with the page, but go over the header (where the rest of the page goes "under" it). Switching sides when switching languages is a nice touch.

**Comment by tbrisker** [comment]
I see what you mean, but if it is behind the header it looks bad too (half of it is covered by the semi-transparent header). Another option is to make it fixed like the header, what do you think?

**Comment by shaib** [comment]
I see two good options: one is to make it fixed like the header, and the other to make it go under the header in the z-sense, while also making it start under the header in the y-sense. Then it is only half-hidden by the header when you scroll down, consistent with other content on the page.

**Comment by tbrisker** [comment]
@shaib updated to keep the ribbon fixed.

**Comment by shaib** [comment]
Site updated after merge

**Pull request merged**
